---
- hosts: vyos-net1
  gather_facts: false
  connection: network_cli

  tasks:

    - name: device interfaces
      vyos_command:
        commands:
          - show interfaces
      register: interfaces

    - name: list interfaces
      debug:
        msg: "{{ interfaces }}"

    - name: current routing table
      vyos_command:
        commands:
          - show ip route
      register: routes

    - name: list routes
      debug:
        msg: "{{ routes }}"

...
