---

- name: configuring ospf loopback
  vyos_config:
    lines:
       - set interfaces dummy dum0 address {{ lo }}
    save: yes

- name: configuring ospf neworks
  vyos_config:
    lines:
      - set protocols ospf area 0 network {{ item }}
    save: yes
  with_items: "{{ node_nets }}"

- name: configure all ospf settings
  vyos_config:
    lines:
      - set protocols ospf default-information originate always
      - set protocols ospf default-information originate metric 10
      - set protocols ospf default-information originate metric-type 2
      - set protocols ospf log-adjacency-changes
      - set protocols ospf parameters router-id {{ dumb }}
      - set protocols ospf redistribute connected metric-type 2
      - set protocols ospf redistribute connected route-map CONNECT
      - set policy route-map CONNECT rule 10 action permit
      - set policy route-map CONNECT rule 10 match interface dum0
    save: yes

...
